apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.memcached.name }}
  labels:
    app: {{ .Values.memcached.name }}
spec:
  replicas: {{ .Values.memcached.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.memcached.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.memcached.name }}
    spec:
      containers:
        - name: {{ .Values.memcached.name }}
          image: memcached:latest
          args:
            - "--memory-limit={{ .Values.memcached.memoryLimit }}"
          ports:
            - containerPort: {{ .Values.memcached.containerPort }}
          resources:
            limits:
              memory: "{{ .Values.memcached.memoryLimit }}Mi"
